// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android: return android;
      case TargetPlatform.iOS:     return ios;
      case TargetPlatform.macOS:   return macos;
      case TargetPlatform.windows: return windows;
      default: throw UnsupportedError('Unsupported platform');
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFuklu8LDUmewQTiAk07sYSDYU0_SAUow',
    appId: '1:1013663923740:android:14dcdd020f798feb9369d9',
    messagingSenderId: '1013663923740',
    projectId: 'aurahub-lester-4b4a9',
    storageBucket: 'aurahub-lester-4b4a9.firebasestorage.app',
  );

  // Keep these as-is or update from Firebase console for other platforms
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFuklu8LDUmewQTiAk07sYSDYU0_SAUow',
    appId: '1:1013663923740:android:14dcdd020f798feb9369d9',
    messagingSenderId: '1013663923740',
    projectId: 'aurahub-lester-4b4a9',
    authDomain: 'aurahub-lester-4b4a9.firebaseapp.com',
    storageBucket: 'aurahub-lester-4b4a9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFuklu8LDUmewQTiAk07sYSDYU0_SAUow',
    appId: '1:1013663923740:android:14dcdd020f798feb9369d9',
    messagingSenderId: '1013663923740',
    projectId: 'aurahub-lester-4b4a9',
    storageBucket: 'aurahub-lester-4b4a9.firebasestorage.app',
    iosBundleId: 'com.example.aurahub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFuklu8LDUmewQTiAk07sYSDYU0_SAUow',
    appId: '1:1013663923740:android:14dcdd020f798feb9369d9',
    messagingSenderId: '1013663923740',
    projectId: 'aurahub-lester-4b4a9',
    storageBucket: 'aurahub-lester-4b4a9.firebasestorage.app',
    iosBundleId: 'com.example.aurahub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFuklu8LDUmewQTiAk07sYSDYU0_SAUow',
    appId: '1:1013663923740:android:14dcdd020f798feb9369d9',
    messagingSenderId: '1013663923740',
    projectId: 'aurahub-lester-4b4a9',
    authDomain: 'aurahub-lester-4b4a9.firebaseapp.com',
    storageBucket: 'aurahub-lester-4b4a9.firebasestorage.app',
  );
}