// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUYLhYz_EpzfFcqqeIkf1gLvAefmzTnIg',
    appId: '1:617426288940:web:0ea47000032c02f187ac89',
    messagingSenderId: '617426288940',
    projectId: 'aurahub-ff49a',
    authDomain: 'aurahub-ff49a.firebaseapp.com',
    storageBucket: 'aurahub-ff49a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyLnspwURMuN-YO6RrvMEOEF_-NiFqRYw',
    appId: '1:617426288940:android:a775afb072c4ff6f87ac89',
    messagingSenderId: '617426288940',
    projectId: 'aurahub-ff49a',
    storageBucket: 'aurahub-ff49a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOAfTczKZ8E5Pk1hN75Se9mRfj7J63Jk0',
    appId: '1:617426288940:ios:dc14bd6746db197287ac89',
    messagingSenderId: '617426288940',
    projectId: 'aurahub-ff49a',
    storageBucket: 'aurahub-ff49a.firebasestorage.app',
    iosBundleId: 'com.example.aurahub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOAfTczKZ8E5Pk1hN75Se9mRfj7J63Jk0',
    appId: '1:617426288940:ios:dc14bd6746db197287ac89',
    messagingSenderId: '617426288940',
    projectId: 'aurahub-ff49a',
    storageBucket: 'aurahub-ff49a.firebasestorage.app',
    iosBundleId: 'com.example.aurahub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUYLhYz_EpzfFcqqeIkf1gLvAefmzTnIg',
    appId: '1:617426288940:web:852a43f50982216587ac89',
    messagingSenderId: '617426288940',
    projectId: 'aurahub-ff49a',
    authDomain: 'aurahub-ff49a.firebaseapp.com',
    storageBucket: 'aurahub-ff49a.firebasestorage.app',
  );
}
